### ISSUE TITLE
Improve ember-inspector integration

### ISSUE THREAD

**Issue by lifeart** [lifeart/glimmer-next#90]
- [ ] Add `in-element` case https://github.com/glimmerjs/glimmer-vm/pull/1560
- [ ] Add `modifiers case https://github.com/glimmerjs/glimmer-vm/pull/1559 https://github.com/emberjs/ember-inspector/pull/2548/files
- [ ] Add rendered slots
- [ ] Add rendered helpers?
- [ ] tracked deps https://github.com/emberjs/ember-inspector/pull/2546/files

![image](https://github.com/lifeart/glimmer-next/assets/1360552/45d8eead-e42e-492d-bd9b-bb775f877afb)
https://discord.com/channels/480462759797063690/1204116134236790835/1204423436051677224

**Comment by lifeart** [comment]
ember_debug.js:6054 failed to setup in element support Error: Module: '@glimmer/runtime' not found.
    at requireModule (ember-inspector.ts:575:13)
    at InElementSupportProvider.require (ember_debug.js:6028:39)
    at new InElementSupportProvider (ember_debug.js:5907:27)
    at new RenderTree (ember_debug.js:6052:33)
    at _class.init (ember_debug.js:10517:42)
    at new BaseObject (ember_debug.js:9660:12)
    at new _default (ember_debug.js:813:7)
    at new _class (ember_debug.js:10508:3)
    at EmberDebug.startModule (ember_debug.js:7318:20)
    at ember_debug.js:7347:14

**Comment by lifeart** [comment]
<img width="757" alt="image" src="https://github.com/user-attachments/assets/8b552dbe-3c5f-40ec-80f1-b41e97ae81a5" />
